// file contains list of albums that should be displayed on site

export let albumList = [
	{
		title: "Master of Reality",
		author: "Black Sabbath",
		year: 1971,
		price: 10.99,
		imgSrc: "Master_of_Reality.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Paranoid",
		author: "Black Sabbath",
		year: 1970,
		price: 25.99,
		imgSrc: "Paranoid.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Vol. 4",
		author: "Black Sabbath",
		year: 1972,
		price: 15.59,
		imgSrc: "Vol_4.jpg",
		filter: false,
		search: false,
	},
	{
		title: "In Rock",
		author: "Deep Purple",
		year: 1970,
		price: 17.29,
		imgSrc: "In_Rock.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Mothership",
		author: "Led Zeppelin",
		year: 2007,
		price: 13.99,
		imgSrc: "Mothership.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Animals",
		author: "Pink Floyd",
		year: 1977,
		price: 9.99,
		imgSrc: "Animals.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Dark Side of the Moon",
		author: "Pink Floyd",
		year: 1973,
		price: 19.99,
		imgSrc: "Dark_Side_of_the_Moon.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Wish You Were Here",
		author: "Pink Floyd",
		year: 1975,
		price: 11.99,
		imgSrc: "Wish_You_Were_Here.jpg",
		filter: false,
		search: false,
	},
	{
		title: "L.A.Woman",
		author: "The Doors",
		year: 1971,
		price: 11.99,
		imgSrc: "LA_Woman.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Morrison Hotel",
		author: "The Doors",
		year: 1970,
		price: 10.99,
		imgSrc: "Morrison_Hotel.jpg",
		filter: false,
		search: false,
	},
	{
		title: "The Doors",
		author: "The Doors",
		year: 1967,
		price: 18.99,
		imgSrc: "The_Doors.jpg",
		filter: false,
		search: false,
	},
	{
		title: "Waiting for the Sun",
		author: "The Doors",
		year: 1968,
		price: 9.99,
		imgSrc: "Waiting_for_the_Sun.jpg",
		filter: false,
		search: false,
	},
];
